#!bin/bash


# ===============================================================================
#
# Merge ROOT files generated directly from grid jobs.
# 
# Those files are usually generated by run number and stored in SCRATCH,
# with a particular process ID depending on the date and hour of submission.
#
# The idea is to merge all of the files corresponding to a particular playlist,
# In the case of MC files, this is ideal since the ME intensity effects are
# shown to be different among playlists, and hence POT-scaling must be done
# in a playlist-by-playlist basis.
#
# Input options in this bash script include:
# -> Macro type whose files have to be merged
# -> MC or data?
# -> Model used (if MC)
# -> Use of systematics universes?
# -> Processing ID (coming from grid output directory in SCRATCH)
#
# ===============================================================================


echo
echo " Merging ROOT files from grid into one file per playlist "
echo " ======================================================= "
echo
echo " Select among the following options: "
echo "   [1]: Event selection, migration matrix, efficiency num & den, and plastic/physics pre-tuning distributions. "
echo "   [2]: Reconstruction cuts studies. "
echo "   [3]: Sideband studies. "
echo "   [4]: Efficiency optimization as function of true muon angle (MC-only). "
echo "   [5]: Fake data models for warping studies (MC-only). "
echo "   [6]: Alternative efficiency distributions (MC-only). "
echo "   [7]: Supporting distributions for different purposes. "
echo
read -p " Which option? " OPT_MACRO
echo



# MC or data?
# ===========

read -p " Are these files MC or data? [mc/data]: " OPT_MC_DATA

if [ "$OPT_MC_DATA" != "mc" ] && [ "$OPT_MC_DATA" != "data" ]; then
    echo
    echo " ERROR: Select either 'mc' or 'data' "
    echo
    return 1
    
elif [ "$OPT_MC_DATA" == "mc" ]; then
    LABEL_MC_DATA="MC_"
    echo
    
elif [ "$OPT_MC_DATA" == "data" ]; then
    LABEL_MC_DATA="Data_"
    echo
    
fi



# Macro name
# ==========

if [ "$OPT_MACRO" == "1" ]; then
    LABEL_MACRO_EVSEL="EventSelection_"
    
    if [ "$OPT_MC_DATA" == "mc" ]; then
        LABEL_MACRO_PLASTUN="BeforePlasticTuning_"
        LABEL_MACRO_PHYSTUN="BeforePhysicsTuning_"
        
    elif [ "$OPT_MC_DATA" == "data" ]; then
        LABEL_MACRO_PLASTUN="PlasticTuning_"
        LABEL_MACRO_PHYSTUN="PhysicsTuning_"
    fi
    
elif [ "$OPT_MACRO" == "2" ]; then
    LABEL_MACRO="CutStudies_"
    
elif [ "$OPT_MACRO" == "3" ]; then
    LABEL_MACRO="SidebandStudies_"
    
elif [ "$OPT_MACRO" == "4" ]; then
    LABEL_MACRO="EfficiencyOptimize_"
    
elif [ "$OPT_MACRO" == "5" ]; then
    LABEL_MACRO="FakeData_"
    
elif [ "$OPT_MACRO" == "6" ]; then
    LABEL_MACRO="EfficiencyAlternative_"
    
elif [ "$OPT_MACRO" == "7" ]; then
    LABEL_MACRO="SupportStudies_"
    
fi



# MC model
# ========

if [ "$OPT_MC_DATA" == "mc" ]; then
    read -p " Enter MC model: " OPT_MODEL
    echo
    
    if [ "$OPT_MODEL" != "v0" ] && [ "$OPT_MODEL" != "v1" ] &&
       [ "$OPT_MODEL" != "v1noNonResPi" ] && [ "$OPT_MODEL" != "v1noD2" ] && [ "$OPT_MODEL" != "v1noPionTune" ] &&
       [ "$OPT_MODEL" != "v2MINOS" ] && [ "$OPT_MODEL" != "v2JOINT" ] && [ "$OPT_MODEL" != "v2NU1PI" ] &&
       [ "$OPT_MODEL" != "v2NUNPI" ] && [ "$OPT_MODEL" != "v2NUPI0" ] && [ "$OPT_MODEL" != "v2MENU1PI" ]; then
        echo
        echo " ERROR: Bad model option, select correct model "
        echo
        return 1
    else
        LABEL_MODEL="MnvGENIE${OPT_MODEL}_"
    fi
    
else
    LABEL_MODEL=""
fi




# Include systematics?
# ====================

if [ "$OPT_MC_DATA" == "mc" ]; then
    read -p " Include systematics? [true/false]: " OPT_SYST
    
    if [ "$OPT_SYST" != "true" ] && [ "$OPT_SYST" != "false" ]; then
        echo
        echo " ERROR: Select either 'true' or 'false' "
        echo
        return 1
        
    elif [ "$OPT_SYST" == "true" ]; then
        LABEL_SYST="WithSyst_"
        
    elif [ "$OPT_SYST" == "false" ]; then
        LABEL_SYST="NoSyst_"
        
    fi
    echo
    
else
    LABEL_SYST=""
fi



# Input/output directories
# ========================

read -p " Enter grid files processing ID directory: " OPT_PROCESS_ID
echo
read -p " Enter date of output directory [YYYY-MM-DD]: " OPT_DATE


if [ "$OPT_MC_DATA" == "mc" ]; then
    OPT_OUTDIR_DATE="${OPT_DATE}_${OPT_MODEL}"
    
elif [ "$OPT_MC_DATA" == "data" ]; then
    OPT_OUTDIR_DATE="${OPT_DATE}"
fi


if [ "$OPT_MACRO" == "1" ]; then
    OPT_INDIR=$SCRATCH/MAT/EventSelection/grid_output/$OPT_PROCESS_ID
    
    if [ "$OPT_MC_DATA" == "mc" ]; then
        OPT_OUTDIR_EVSEL_LEAD=$PNFS/MAT/EventSelection/mc/$OPT_OUTDIR_DATE/lead/
        OPT_OUTDIR_EVSEL_IRON=$PNFS/MAT/EventSelection/mc/$OPT_OUTDIR_DATE/iron/
        
        OPT_OUTDIR_PLASTUN_LEAD=$PNFS/MAT/PlasticTuning/mc/$OPT_OUTDIR_DATE/lead/BeforeTuning
        OPT_OUTDIR_PLASTUN_IRON=$PNFS/MAT/PlasticTuning/mc/$OPT_OUTDIR_DATE/iron/BeforeTuning
        OPT_DIR_PLASTUN_AFTER_LEAD=$PNFS/MAT/PlasticTuning/mc/$OPT_OUTDIR_DATE/lead/AfterTuning
        OPT_DIR_PLASTUN_AFTER_IRON=$PNFS/MAT/PlasticTuning/mc/$OPT_OUTDIR_DATE/iron/AfterTuning
        
        OPT_OUTDIR_PHYSTUN_LEAD=$PNFS/MAT/PhysicsTuning/mc/$OPT_OUTDIR_DATE/lead/BeforeTuning
        OPT_OUTDIR_PHYSTUN_IRON=$PNFS/MAT/PhysicsTuning/mc/$OPT_OUTDIR_DATE/iron/BeforeTuning
        OPT_DIR_PHYSTUN_AFTER_LEAD=$PNFS/MAT/PhysicsTuning/mc/$OPT_OUTDIR_DATE/lead/AfterTuning
        OPT_DIR_PHYSTUN_AFTER_IRON=$PNFS/MAT/PhysicsTuning/mc/$OPT_OUTDIR_DATE/iron/AfterTuning
        
    elif [ "$OPT_MC_DATA" == "data" ]; then
        OPT_OUTDIR_EVSEL_LEAD=$PNFS/MAT/EventSelection/data/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_EVSEL_IRON=$PNFS/MAT/EventSelection/data/$OPT_OUTDIR_DATE/iron
        
        OPT_OUTDIR_PLASTUN_LEAD=$PNFS/MAT/PlasticTuning/data/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_PLASTUN_IRON=$PNFS/MAT/PlasticTuning/data/$OPT_OUTDIR_DATE/iron
        
        OPT_OUTDIR_PHYSTUN_LEAD=$PNFS/MAT/PhysicsTuning/data/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_PHYSTUN_IRON=$PNFS/MAT/PhysicsTuning/data/$OPT_OUTDIR_DATE/iron
    fi
    
    mkdir -p $OPT_OUTDIR_EVSEL_LEAD
    mkdir -p $OPT_OUTDIR_EVSEL_IRON
    
    mkdir -p $OPT_OUTDIR_PLASTUN_LEAD
    mkdir -p $OPT_OUTDIR_PLASTUN_IRON
    mkdir -p $OPT_DIR_PLASTUN_AFTER_LEAD
    mkdir -p $OPT_DIR_PLASTUN_AFTER_IRON
    
    mkdir -p $OPT_OUTDIR_PHYSTUN_LEAD
    mkdir -p $OPT_OUTDIR_PHYSTUN_IRON
    mkdir -p $OPT_DIR_PHYSTUN_AFTER_LEAD
    mkdir -p $OPT_DIR_PHYSTUN_AFTER_IRON
    
    
elif [ "$OPT_MACRO" == "2" ]; then
    OPT_INDIR=$SCRATCH/MAT/CutStudies/grid_output/$OPT_PROCESS_ID
    
    if [ "$OPT_MC_DATA" == "mc" ]; then
        OPT_OUTDIR_LEAD=$PNFS/MAT/CutStudies/mc/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_IRON=$PNFS/MAT/CutStudies/mc/$OPT_OUTDIR_DATE/iron
        
    elif [ "$OPT_MC_DATA" == "data" ]; then
        OPT_OUTDIR_LEAD=$PNFS/MAT/CutStudies/data/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_IRON=$PNFS/MAT/CutStudies/data/$OPT_OUTDIR_DATE/iron
    fi
    
    mkdir -p $OPT_OUTDIR_LEAD
    mkdir -p $OPT_OUTDIR_IRON
    
    
elif [ "$OPT_MACRO" == "3" ]; then
    OPT_INDIR=$SCRATCH/MAT/SidebandStudies/grid_output/$OPT_PROCESS_ID
    
    if [ "$OPT_MC_DATA" == "mc" ]; then
        OPT_OUTDIR_LEAD=$PNFS/MAT/SidebandStudies/mc/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_IRON=$PNFS/MAT/SidebandStudies/mc/$OPT_OUTDIR_DATE/iron
        
    elif [ "$OPT_MC_DATA" == "data" ]; then
        OPT_OUTDIR_LEAD=$PNFS/MAT/SidebandStudies/data/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_IRON=$PNFS/MAT/SidebandStudies/data/$OPT_OUTDIR_DATE/iron
    fi
    
    mkdir -p $OPT_OUTDIR_LEAD
    mkdir -p $OPT_OUTDIR_IRON
    
    
elif [ "$OPT_MACRO" == "4" ] || [ "$OPT_MACRO" == "6" ]; then
    OPT_INDIR=$SCRATCH/MAT/EfficiencyStudies/grid_output/$OPT_PROCESS_ID
    
    if [ "$OPT_MC_DATA" == "mc" ]; then
        OPT_OUTDIR_LEAD=$PNFS/MAT/EfficiencyStudies/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_IRON=$PNFS/MAT/EfficiencyStudies/$OPT_OUTDIR_DATE/iron
    fi
    
    mkdir -p $OPT_OUTDIR_LEAD
    mkdir -p $OPT_OUTDIR_IRON
    
    
elif [ "$OPT_MACRO" == "5" ]; then
    OPT_INDIR=$SCRATCH/MAT/FakeDataModels/grid_output/$OPT_PROCESS_ID
    
    if [ "$OPT_MC_DATA" == "mc" ]; then
        OPT_OUTDIR_LEAD=$PNFS/MAT/FakeDataModels/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_IRON=$PNFS/MAT/FakeDataModels/$OPT_OUTDIR_DATE/iron
    fi
    
    mkdir -p $OPT_OUTDIR_LEAD
    mkdir -p $OPT_OUTDIR_IRON
    
    
elif [ "$OPT_MACRO" == "7" ]; then
    OPT_INDIR=$SCRATCH/MAT/SupportStudies/grid_output/$OPT_PROCESS_ID
    
    if [ "$OPT_MC_DATA" == "mc" ]; then
        OPT_OUTDIR_LEAD=$PNFS/MAT/SupportStudies/mc/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_IRON=$PNFS/MAT/SupportStudies/mc/$OPT_OUTDIR_DATE/iron
    
    elif [ "$OPT_MC_DATA" == "data" ]; then
        OPT_OUTDIR_LEAD=$PNFS/MAT/SupportStudies/data/$OPT_OUTDIR_DATE/lead
        OPT_OUTDIR_IRON=$PNFS/MAT/SupportStudies/data/$OPT_OUTDIR_DATE/iron
    fi
    
    mkdir -p $OPT_OUTDIR_LEAD
    mkdir -p $OPT_OUTDIR_IRON
    
fi
echo



# Get playlists
declare -a playlists=("minervame1A" "minervame1B" "minervame1C" "minervame1D"
                      "minervame1E" "minervame1F" "minervame1G" "minervame1L"
                      "minervame1M" "minervame1N" "minervame1O" "minervame1P")


# Print input directory
echo " Using input directory: " $OPT_INDIR
echo



# Merge files for event selection and pre-tuning distributions
# ============================================================

if [ "$OPT_MACRO" == "1" ]; then
    
    # Event selection distributions on LEAD
    cd $OPT_OUTDIR_EVSEL_LEAD
    echo " Merging EVENT SELECTION grid files on LEAD to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO_EVSEL}${LABEL_MODEL}${LABEL_SYST}${playlist}_lead.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO_EVSEL}*lead*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    # Event selection distributions on IRON
    cd $OPT_OUTDIR_EVSEL_IRON
    echo " Merging EVENT SELECTION grid files on IRON to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO_EVSEL}${LABEL_MODEL}${LABEL_SYST}${playlist}_iron.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO_EVSEL}*iron*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    # Pre-plastic tuning distributions on LEAD
    cd $OPT_OUTDIR_PLASTUN_LEAD
    echo " Merging PRE-PLASTIC TUNING grid files on LEAD to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO_PLASTUN}${LABEL_MODEL}${LABEL_SYST}${playlist}_lead.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO_PLASTUN}*lead*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    # Pre-plastic tuning distributions on IRON
    cd $OPT_OUTDIR_PLASTUN_IRON
    echo " Merging PRE-PLASTIC TUNING grid files on IRON to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO_PLASTUN}${LABEL_MODEL}${LABEL_SYST}${playlist}_iron.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO_PLASTUN}*iron*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    # Pre-physics tuning distributions on LEAD
    cd $OPT_OUTDIR_PHYSTUN_LEAD
    echo " Merging PRE-PHYSICS TUNING grid files on LEAD to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO_PHYSTUN}${LABEL_MODEL}${LABEL_SYST}${playlist}_lead.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO_PHYSTUN}*lead*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    # Pre-physics tuning distributions on IRON
    cd $OPT_OUTDIR_PHYSTUN_IRON
    echo " Merging PRE-PHYSICS TUNING grid files on IRON to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO_PHYSTUN}${LABEL_MODEL}${LABEL_SYST}${playlist}_iron.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO_PHYSTUN}*iron*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    
# Merge files for macros running MC and/or data
# =============================================

elif [ "$OPT_MACRO" == "2" ] || [ "$OPT_MACRO" == "3" ] || [ "$OPT_MACRO" == "7" ]; then
    
    # Distributions on LEAD
    cd $OPT_OUTDIR_LEAD
    echo " Merging grid files on LEAD to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO}${LABEL_MODEL}${LABEL_SYST}${playlist}_lead.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO}*lead*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    # Distributions on IRON
    cd $OPT_OUTDIR_IRON
    echo " Merging grid files on IRON to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO}${LABEL_MODEL}${LABEL_SYST}${playlist}_iron.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO}*iron*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    
# Merge files for MC-only macros
# ==============================

elif [ "$OPT_MACRO" == "4" ] || [ "$OPT_MACRO" == "5" ] || [ "$OPT_MACRO" == "6" ]; then
    
    # Distributions on LEAD
    cd $OPT_OUTDIR_LEAD
    echo " Merging grid files on LEAD to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO}${LABEL_MODEL}${LABEL_SYST}${playlist}_lead.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO}*lead*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
    
    # Distributions on IRON
    cd $OPT_OUTDIR_IRON
    echo " Merging grid files on IRON to directory: " $PWD
    
    for playlist in "${playlists[@]}"; do
        if [ -d "${OPT_INDIR}/${playlist}" ]; then
            echo "   Merging grid files of playlist" ${playlist}
            madd ${LABEL_MC_DATA}${LABEL_MACRO}${LABEL_MODEL}${LABEL_SYST}${playlist}_iron.root ${OPT_INDIR}/${playlist}/${LABEL_MC_DATA}${LABEL_MACRO}*iron*.root
            echo "   Done merging for playlist" ${playlist}
            echo
        fi
    done
    echo
    
fi


# Return to CCPi0_Macros directory
cd $CCPI0MACROS
